name: Secret and Variable Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  demo-job:
    runs-on: ubuntu-latest
    env:
      GLOBAL_ENV_VAR: "This is a global environment variable"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      # SECRET
    - name: Demo GitHub Secrets
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
      run: |
        echo "Original secret: $MY_SECRET"
        echo "Reversed twice: $(echo $MY_SECRET | rev | rev)"
        echo "Without last char: ${MY_SECRET%?}"
        echo "Uppercase: $(echo $MY_SECRET | tr '[:lower:]' '[:upper:]')"
        echo "With prefix: PREFIX_$MY_SECRET"

      # VARIABLE
    - name: Demo GitHub Variables
      env:
        MY_VARIABLE: ${{ vars.MY_VARIABLE }}
      run: |
        echo "The variable value is: $MY_VARIABLE"


  environment-job:
    runs-on: ubuntu-latest
    environment: dev
    env:
      GLOBAL_ENV_VAR: "This is a global environment variable for dev"
    
    steps:
    - name: Demo GitHub Secrets
      # SECRET
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
      run: |
        echo "Original secret: $MY_SECRET"
        echo "First 3 chars: ${MY_SECRET:0:3}"
        echo "Last 3 chars: ${MY_SECRET: -3}"
        echo "Lowercase: $(echo $MY_SECRET | tr '[:upper:]' '[:lower:]')"
        echo "With suffix: $MY_SECRET_SUFFIX"

      # VARIABLE
    - name: Demo GitHub Variables
      env:
        MY_VARIABLE: ${{ vars.MY_VARIABLE }}
      run: |
        echo "The variable value is: $MY_VARIABLE"

      # VARIABLE
    - name: Demo Environment-Specific Variable
      env:
        DEV_SPECIFIC_VAR: ${{ vars.DEV_SPECIFIC_VAR }}
      run: |
        echo "The dev-specific variable is: $DEV_SPECIFIC_VAR"

      # ENV SECRET
    - name: Demo Environment-Specific Secret
      env:
        DEV_SECRET: ${{ secrets.DEV_SECRET }}
      run: |
        echo "Original dev secret: $DEV_SECRET"
        echo "Reversed dev secret: $(echo $DEV_SECRET | rev)"
        echo "First 5 chars of dev secret: ${DEV_SECRET:0:5}"
        echo "Dev secret with prefix: DEV_PREFIX_$DEV_SECRET"
